import React from 'react';

interface FlowLegalFooterProps {
  className?: string;
}

const FlowLegalFooter: React.FC<FlowLegalFooterProps> = ({ className = '' }) => {
  return (
    <footer className={`mt-8 ${className}`}>
      <div className="max-w-6xl mx-auto px-4">
        <div className="rounded-2xl border border-[#d9dfeb] bg-white/85 backdrop-blur-sm p-5 md:p-6 text-[#5f6b7b] shadow-sm">
          <p className="text-[11px] md:text-xs leading-relaxed">
            Dent-Vision AI provides AI-assisted repair estimates based on the photos submitted, regional pricing logic,
            and automated damage analysis. All values shown on this platform are estimates only and may vary depending
            on the final inspection performed by the selected bodyshop.
          </p>

          <p className="text-[11px] md:text-xs leading-relaxed mt-3">
            Repair pricing, repair methods, timing, and final approval are determined solely by the independent repair
            shop or technician reviewing the vehicle. Hidden damage, panel access, paint condition, material type, and
            additional repairs may affect the final quote.
          </p>

          <p className="text-[11px] md:text-xs leading-relaxed mt-3">
            Dent-Vision AI acts exclusively as a technology platform connecting customers with participating repair
            partners and does not guarantee final pricing, repair outcomes, availability, or workmanship provided by
            third-party bodyshops.
          </p>

          <p className="text-[11px] md:text-xs leading-relaxed mt-4 font-semibold text-[#374151]">
            By using this platform, you acknowledge and agree that:
          </p>

          <ul className="text-[11px] md:text-xs leading-relaxed mt-2 list-disc pl-5 space-y-1">
            <li>estimates generated by AI are indicative only;</li>
            <li>final pricing may increase or decrease after physical inspection;</li>
            <li>each bodyshop operates independently and sets its own repair pricing and conditions;</li>
            <li>
              Dent-Vision AI and its partners are not liable for quote differences, repair decisions, or additional costs
              identified during inspection or repair.
            </li>
          </ul>

          <p className="text-[11px] md:text-xs leading-relaxed mt-4 text-[#334155] font-medium">
            We strongly recommend confirming all repair details directly with the selected repair shop before proceeding
            with any service.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default FlowLegalFooter;
