import { corsHeaders, fail, ok } from '../_shared/response.ts';
import { generateGeminiJson } from '../_shared/gemini.ts';

type AnalyzeLiveScanInput = {
  frames?: string[];
  vehicleDetails?: {
    vehicleType?: string;
  };
};

type AnalyzeLiveScanModelResponse = {
  dent_count: number;
  scratch_count: number;
  severity: 'Minor' | 'Moderate' | 'Severe' | 'Unknown';
  confidence: number;
  notes?: string;
};

const LIVE_SCAN_ANALYSIS_PROMPT = [
  'You are an expert automotive dent analysis assistant for live camera scans.',
  'Analyze all frames together as the same vehicle panel sequence, not as separate jobs.',
  'Count visible dents conservatively and avoid double-counting the same dent across angles/frames.',
  'Focus on: dent_count, scratch_count, severity, confidence, and short notes.',
  'Use vehicle references to estimate size and severity when possible:',
  '- Door handle: ~180-200mm',
  '- Fuel cap: ~150-180mm',
  '- Wheel diameter: ~400-500mm',
  'Severity guidance:',
  '- Minor: mostly small/shallow dents',
  '- Moderate: multiple visible dents or medium deformation',
  '- Severe: large/deep dents, crease-like damage, or broad panel distortion',
  'If frames are blurry, dark, or inconsistent, reduce confidence accordingly.',
  'Return ONLY strict JSON: {"dent_count":number,"scratch_count":number,"severity":"Minor|Moderate|Severe|Unknown","confidence":number,"notes":string}.',
].join('\n');

const fallbackPayload = (vehicleType: string) => ({
  panels: [
    {
      panel_name: 'doors',
      dent_count: 2,
      scratch_count: 0,
      modifiers: {
        aluminium: false,
        access_difficulty: 'low',
        hail_cluster: false,
      },
      estimated_panel_cost_AUD: { min: 240, max: 370 },
      dents: [],
      scratches: [],
    },
  ],
  summary: {
    vehicle_type: vehicleType,
    total_dents: 2,
    total_scratches: 0,
    overall_severity: 'Minor',
    base_callout_applied: false,
    estimated_total_cost_AUD: { min: 240, max: 370 },
    confidence_overall: 0.84,
  },
  flags: {
    review_required: false,
    possible_reflection: false,
    pdr_incompatible: false,
  },
  notes: 'Fallback live-scan response.',
});

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return fail('Method not allowed', 'METHOD_NOT_ALLOWED', 405);
  }

  try {
    const body = (await req.json()) as AnalyzeLiveScanInput;
    const frames = Array.isArray(body.frames) ? body.frames : [];
    const vehicleType = body.vehicleDetails?.vehicleType || 'sedan';

    if (!frames.length) {
      return fail('No frames provided', 'INVALID_PAYLOAD', 400);
    }

    try {
      const modelResult = await generateGeminiJson<AnalyzeLiveScanModelResponse>(
        LIVE_SCAN_ANALYSIS_PROMPT,
        frames.slice(0, 6).map((base64) => ({ base64, mimeType: 'image/jpeg' })),
      );

      const dentCount = Math.max(0, Math.round(modelResult.dent_count || 0));
      const scratchCount = Math.max(0, Math.round(modelResult.scratch_count || 0));
      const min = Math.max(120, 190 + dentCount * 45 + scratchCount * 30);
      const max = min + 130;

      return ok({
        panels: [
          {
            panel_name: 'doors',
            dent_count: dentCount,
            scratch_count: scratchCount,
            modifiers: {
              aluminium: false,
              access_difficulty: dentCount > 3 ? 'medium' : 'low',
              hail_cluster: false,
            },
            estimated_panel_cost_AUD: { min, max },
            dents: [],
            scratches: [],
          },
        ],
        summary: {
          vehicle_type: vehicleType,
          total_dents: dentCount,
          total_scratches: scratchCount,
          overall_severity: modelResult.severity || 'Minor',
          base_callout_applied: false,
          estimated_total_cost_AUD: { min, max },
          confidence_overall: Math.min(0.99, Math.max(0.45, Number(modelResult.confidence || 0.82))),
        },
        flags: {
          review_required: dentCount > 6,
          possible_reflection: false,
          pdr_incompatible: scratchCount > 2,
        },
        notes: modelResult.notes || 'Generated by Gemini live-scan analysis.',
      });
    } catch (modelError) {
      console.warn('[analyze-live-scan] Gemini unavailable, using fallback', modelError);
      return ok(fallbackPayload(vehicleType));
    }
  } catch (error) {
    console.error('[analyze-live-scan] error', error);
    return fail('Invalid request body', 'INVALID_JSON', 400);
  }
});
